import { afterEach, describe, expect, it, vi } from 'vitest'
import { remainingPercent, UsageStore, windowLabel } from './UsageStore'

afterEach(() => vi.useRealTimers())
describe('account quota', () => {
  it('converts consumed percentage without treating missing values as zero', () => {
    expect(remainingPercent(4)).toBe(96)
    expect(remainingPercent(16)).toBe(84)
    expect(remainingPercent(110)).toBe(0)
    expect(remainingPercent(-5)).toBe(100)
    expect(remainingPercent(null)).toBeNull()
    expect(remainingPercent(NaN)).toBeNull()
    expect(windowLabel(300, '?')).toBe('5 小时')
    expect(windowLabel(10080, '?')).toBe('1 周')
    expect(windowLabel(15, '?')).toBe('15 分钟')
  })
  it('correlates responses, clears offline values and refetches on reconnect', () => {
    const send = vi.fn().mockReturnValueOnce('one').mockReturnValue('two')
    const store = new UsageStore(send)
    store.setOnline(true)
    const response = { type: 'account.rateLimits.response', requestId: 'one', timestamp: 0, payload: { buckets: [], fetchedAt: 123 } }
    expect(store.apply({ ...response, requestId: 'unrelated' })).toBe(false)
    expect(store.apply(response)).toBe(true)
    expect(store.getSnapshot().data?.fetchedAt).toBe(123)
    store.setOnline(false)
    expect(store.getSnapshot().data).toBeUndefined()
    store.setOnline(true)
    expect(send).toHaveBeenCalledTimes(2)
    expect(store.apply(response)).toBe(false)
    store.dispose()
  })
  it('times out older bridges without retry storms; manual retry recovers', () => {
    vi.useFakeTimers()
    const send = vi.fn(() => 'request')
    const store = new UsageStore(send)
    store.setOnline(true)
    store.refresh()
    expect(send).toHaveBeenCalledTimes(1)
    vi.advanceTimersByTime(35_000)
    expect(store.getSnapshot().loading).toBe(false)
    expect(store.getSnapshot().error).toBeTruthy()
    store.refresh(true)
    expect(send).toHaveBeenCalledTimes(1)
    store.refresh()
    expect(send).toHaveBeenCalledTimes(2)
    expect(store.apply({ type: 'error', requestId: 'request', timestamp: 0, payload: { message: 'raw secret' } })).toBe(true)
    expect(store.getSnapshot().error).not.toContain('raw secret')
    store.dispose()
  })
})
